pipeline {
    agent any
    tools {
        maven "Maven 3.8.6"
        jdk "jdk11"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/kaushiki-bhattacharya-001/maven-project.git'
            }
            post {
                success {
                    echo "Pulling from ..." + git.BRANCH_NAME
                }
            }
        }
        stage('Build') {
            steps {
                sh "mvn -f training/pom.xml -Dmaven.test.skip=true clean compile"
            }
            post {
                success {
                    echo "COMPILATION SUCCESSFUL!"
                }
            }
        }
        stage('Test') {
            steps {
                sh "mvn test"
            }
            post {
                success {
                    echo "TEST SUCCESSFUL!"
                }
            }
        }
        stage('Package') {
            steps {
                sh "mvn package"
            }
            post {
                success {
                    echo "PACKAGE SUCCESSFUL!"
                }
            }
        }
        stage('Deploy') {
            steps {
            }
            post {
                success {
                    echo "DEPLOYMENT SUCCESSFUL!"
                }
            }
        }
    }
}
