pipeline {
    agent any
    tools {
        maven "Maven 3.8.6"
        jdk "jdk11"
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/kaushiki-bhattacharya-001/maven-project.git'
                sh "mvn -f training/pom.xml -Dmaven.test.skip=true clean compile"
            }
            post {
                success {
                    echo "COMPILATION SUCCESSFUL!"
                }
            }
        }
        stage('Test') {
            steps {
                sh "mvn -f training/pom.xml test"
            }
            post {
                success {
                    echo "TEST SUCCESSFUL!"
                }
            }
        }
        stage('Package') {
            steps {
                sh "mvn -f training/pom.xml package"
            }
            post {
                success {
                    echo "PACKAGE SUCCESSFUL!"
                }
            }
        }
        stage('Deploy') {
            steps {
                // Install and configure Minikube
                sh 'curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64'
                sh 'sudo install minikube-linux-amd64 /usr/local/bin/minikube'
                sh 'minikube start --driver=docker'
                sh 'docker build -t training/target/scholar-project.jar .'
                sh 'minikube image load scholar-project.jar:latest'
                sh 'kubectl apply -f training/deployment.yaml'
            }
            post {
                success {
                    echo "DEPLOYMENT SUCCESSFUL!"
                }
            }
        }
    }
}
